# Generated by Django 5.2.9 on 2026-01-06 21:11

import config.storages
import django.db.models.deletion
import dkmovie.upload.fields
import dkmovie.videos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the video', primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='The ID of the object this video belongs to')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='The status of the video processing', max_length=20)),
                ('source_file', dkmovie.upload.fields.S3FileField(blank=True, help_text='The video file', max_length=500, null=True, storage=config.storages.PrivateMediaStorage(), upload_to=dkmovie.videos.models.source_file_path)),
                ('hls_playlist', dkmovie.upload.fields.S3FileField(blank=True, help_text='The HLS master playlist file', max_length=500, null=True, storage=config.storages.PrivateMediaStorage(), upload_to=dkmovie.videos.models.hls_playlist_path)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('duration', models.PositiveIntegerField(default=0, help_text='The duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the video was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the video was last updated')),
                ('content_type', models.ForeignKey(help_text='The type of the object this video belongs to (Title or Episode)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='videos_vide_content_6d1d17_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_video_per_object')],
            },
        ),
    ]
