# Generated by Django 5.2.9 on 2026-01-08 00:44

import django.db.models.deletion
import dkmovie.videos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSprite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the sprite sheet', primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='The sprite sheet image file (JPEG)', upload_to=dkmovie.videos.models.get_sprite_file_path)),
                ('start_time', models.PositiveIntegerField(help_text='Time in seconds where this sprite sheet starts (e.g., 0)')),
                ('end_time', models.PositiveIntegerField(help_text='Time in seconds where this sprite sheet ends')),
                ('interval', models.PositiveIntegerField(default=10, help_text='Interval in seconds between each thumbnail')),
                ('frame_width', models.PositiveIntegerField(help_text='Width of a single thumbnail in pixels')),
                ('frame_height', models.PositiveIntegerField(help_text='Height of a single thumbnail in pixels')),
                ('columns', models.PositiveIntegerField(help_text='Number of columns in the sprite sheet grid')),
                ('rows', models.PositiveIntegerField(help_text='Number of rows in the sprite sheet grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(help_text='The video this sprite belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sprites', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Sprite',
                'verbose_name_plural': 'Video Sprites',
                'ordering': ['video', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('video', 'start_time'), name='unique_sprite_start_time_per_video')],
            },
        ),
    ]
