# Generated by Django 5.2.9 on 2026-01-12 21:28

import config.storages
import django.db.models.deletion
import dkmovie.upload.fields
import dkmovie.videos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videosprite'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the media track', primary_key=True, serialize=False)),
                ('language', models.CharField(default='pt-br', help_text="Language code (e.g., 'en', 'pt-br')", max_length=10)),
                ('label', models.CharField(default='Português', help_text="Label shown to the user (e.g., 'English', 'Português')", max_length=50)),
                ('is_original', models.BooleanField(default=False, help_text='If true, this track is the original language track.')),
                ('subtitle_file', dkmovie.upload.fields.S3FileField(blank=True, help_text='The WebVTT subtitle file (.vtt)', max_length=500, null=True, storage=config.storages.PrivateMediaStorage(), upload_to=dkmovie.videos.models.subtitle_file_path)),
                ('audio_playlist', dkmovie.upload.fields.S3FileField(blank=True, help_text='The HLS manifest for the audio track (.m3u8)', max_length=500, null=True, storage=config.storages.PrivateMediaStorage(), upload_to=dkmovie.videos.models.audio_playlist_file_path)),
                ('source_audio_index', models.IntegerField(blank=True, help_text='Original FFmpeg stream index for the audio (if extracted)', null=True)),
                ('source_subtitle_index', models.IntegerField(blank=True, help_text='Original FFmpeg stream index for the subtitle (if extracted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(help_text='The video this track belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='videos.video')),
            ],
            options={
                'verbose_name': 'Media Track',
                'verbose_name_plural': 'Media Tracks',
                'ordering': ['language', 'label'],
                'constraints': [models.UniqueConstraint(fields=('video', 'language'), name='unique_language_per_video')],
            },
        ),
    ]
