# Generated by Django 5.2.10 on 2026-01-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videotrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotrack',
            name='label_en_us',
            field=models.CharField(default='Português', help_text="Label shown to the user (e.g., 'English', 'Português')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='label_pt_br',
            field=models.CharField(default='Português', help_text="Label shown to the user (e.g., 'English', 'Português')", max_length=50, null=True),
        ),
    ]
