# Generated by Django 5.2.10 on 2026-01-19 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videotrack_label_en_us_videotrack_label_pt_br'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('recap', 'Recap'), ('intro', 'Intro'), ('credits', 'Credits (Next Ep)')], help_text='Type of marker', max_length=20)),
                ('start_time', models.PositiveIntegerField(help_text='Time in seconds when the event starts')),
                ('end_time', models.PositiveIntegerField(help_text='Time in seconds when the event ends')),
                ('video', models.ForeignKey(help_text='The video this marker belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Marker',
                'verbose_name_plural': 'Video Markers',
                'ordering': ['video', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('video', 'label', 'start_time'), name='unique_marker_per_video_start_time')],
            },
        ),
    ]
