# Generated by Django 5.2.10 on 2026-01-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videomarker'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='videomarker',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_greater_than_start_time'),
        ),
    ]
