# Generated by Django 5.2.10 on 2026-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videomarker_end_time_greater_than_start_time'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='videomarker',
            name='unique_marker_per_video_start_time',
            constraint=models.UniqueConstraint(fields=('video', 'label', 'start_time'), name='unique_marker_per_video_start_time', violation_error_message='Marker with this label and start time already exists for this video'),
        ),
        migrations.AlterConstraint(
            model_name='videomarker',
            name='end_time_greater_than_start_time',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_greater_than_start_time', violation_error_message='End time must be greater than start time'),
        ),
    ]
