/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MoviesRouteImport } from "./routes/movies"
import { Route as AuthRouteRouteImport } from "./routes/auth/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TitleTitleIdRouteImport } from "./routes/title/$titleId"
import { Route as AuthSignUpRouteImport } from "./routes/auth/sign-up"
import { Route as AuthSignInRouteImport } from "./routes/auth/sign-in"
import { Route as AccountVerifyEmailRouteImport } from "./routes/account/verify-email"
import { Route as Auth2faRouteRouteImport } from "./routes/auth/2fa/route"
import { Route as AccountmyAccountRouteRouteImport } from "./routes/account/(my-account)/route"
import { Route as Auth2faIndexRouteImport } from "./routes/auth/2fa/index"
import { Route as AccountmyAccountIndexRouteImport } from "./routes/account/(my-account)/index"
import { Route as TitleTitleIdWatchRouteImport } from "./routes/title/$titleId.watch"
import { Route as AuthPasswordResetRouteImport } from "./routes/auth/password/reset"
import { Route as AuthPasswordForgotRouteImport } from "./routes/auth/password/forgot"
import { Route as Auth2faTotpRouteImport } from "./routes/auth/2fa/totp"
import { Route as Auth2faRecoveryCodesRouteImport } from "./routes/auth/2fa/recovery-codes"
import { Route as AccountProviderCallbackRouteImport } from "./routes/account/provider.callback"
import { Route as AccountmyAccountSecurityRouteImport } from "./routes/account/(my-account)/security"

const MoviesRoute = MoviesRouteImport.update({
  id: "/movies",
  path: "/movies",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TitleTitleIdRoute = TitleTitleIdRouteImport.update({
  id: "/title/$titleId",
  path: "/title/$titleId",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AccountVerifyEmailRoute = AccountVerifyEmailRouteImport.update({
  id: "/account/verify-email",
  path: "/account/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const Auth2faRouteRoute = Auth2faRouteRouteImport.update({
  id: "/2fa",
  path: "/2fa",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AccountmyAccountRouteRoute = AccountmyAccountRouteRouteImport.update({
  id: "/account/(my-account)",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any)
const Auth2faIndexRoute = Auth2faIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => Auth2faRouteRoute,
} as any)
const AccountmyAccountIndexRoute = AccountmyAccountIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AccountmyAccountRouteRoute,
} as any)
const TitleTitleIdWatchRoute = TitleTitleIdWatchRouteImport.update({
  id: "/watch",
  path: "/watch",
  getParentRoute: () => TitleTitleIdRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: "/password/reset",
  path: "/password/reset",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPasswordForgotRoute = AuthPasswordForgotRouteImport.update({
  id: "/password/forgot",
  path: "/password/forgot",
  getParentRoute: () => AuthRouteRoute,
} as any)
const Auth2faTotpRoute = Auth2faTotpRouteImport.update({
  id: "/totp",
  path: "/totp",
  getParentRoute: () => Auth2faRouteRoute,
} as any)
const Auth2faRecoveryCodesRoute = Auth2faRecoveryCodesRouteImport.update({
  id: "/recovery-codes",
  path: "/recovery-codes",
  getParentRoute: () => Auth2faRouteRoute,
} as any)
const AccountProviderCallbackRoute = AccountProviderCallbackRouteImport.update({
  id: "/account/provider/callback",
  path: "/account/provider/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountmyAccountSecurityRoute =
  AccountmyAccountSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => AccountmyAccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/auth": typeof AuthRouteRouteWithChildren
  "/movies": typeof MoviesRoute
  "/account": typeof AccountmyAccountRouteRouteWithChildren
  "/auth/2fa": typeof Auth2faRouteRouteWithChildren
  "/account/verify-email": typeof AccountVerifyEmailRoute
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/title/$titleId": typeof TitleTitleIdRouteWithChildren
  "/account/security": typeof AccountmyAccountSecurityRoute
  "/account/provider/callback": typeof AccountProviderCallbackRoute
  "/auth/2fa/recovery-codes": typeof Auth2faRecoveryCodesRoute
  "/auth/2fa/totp": typeof Auth2faTotpRoute
  "/auth/password/forgot": typeof AuthPasswordForgotRoute
  "/auth/password/reset": typeof AuthPasswordResetRoute
  "/title/$titleId/watch": typeof TitleTitleIdWatchRoute
  "/account/": typeof AccountmyAccountIndexRoute
  "/auth/2fa/": typeof Auth2faIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/auth": typeof AuthRouteRouteWithChildren
  "/movies": typeof MoviesRoute
  "/account/verify-email": typeof AccountVerifyEmailRoute
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/title/$titleId": typeof TitleTitleIdRouteWithChildren
  "/account/security": typeof AccountmyAccountSecurityRoute
  "/account/provider/callback": typeof AccountProviderCallbackRoute
  "/auth/2fa/recovery-codes": typeof Auth2faRecoveryCodesRoute
  "/auth/2fa/totp": typeof Auth2faTotpRoute
  "/auth/password/forgot": typeof AuthPasswordForgotRoute
  "/auth/password/reset": typeof AuthPasswordResetRoute
  "/title/$titleId/watch": typeof TitleTitleIdWatchRoute
  "/account": typeof AccountmyAccountIndexRoute
  "/auth/2fa": typeof Auth2faIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/auth": typeof AuthRouteRouteWithChildren
  "/movies": typeof MoviesRoute
  "/account/(my-account)": typeof AccountmyAccountRouteRouteWithChildren
  "/auth/2fa": typeof Auth2faRouteRouteWithChildren
  "/account/verify-email": typeof AccountVerifyEmailRoute
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/title/$titleId": typeof TitleTitleIdRouteWithChildren
  "/account/(my-account)/security": typeof AccountmyAccountSecurityRoute
  "/account/provider/callback": typeof AccountProviderCallbackRoute
  "/auth/2fa/recovery-codes": typeof Auth2faRecoveryCodesRoute
  "/auth/2fa/totp": typeof Auth2faTotpRoute
  "/auth/password/forgot": typeof AuthPasswordForgotRoute
  "/auth/password/reset": typeof AuthPasswordResetRoute
  "/title/$titleId/watch": typeof TitleTitleIdWatchRoute
  "/account/(my-account)/": typeof AccountmyAccountIndexRoute
  "/auth/2fa/": typeof Auth2faIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/auth"
    | "/movies"
    | "/account"
    | "/auth/2fa"
    | "/account/verify-email"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/title/$titleId"
    | "/account/security"
    | "/account/provider/callback"
    | "/auth/2fa/recovery-codes"
    | "/auth/2fa/totp"
    | "/auth/password/forgot"
    | "/auth/password/reset"
    | "/title/$titleId/watch"
    | "/account/"
    | "/auth/2fa/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/auth"
    | "/movies"
    | "/account/verify-email"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/title/$titleId"
    | "/account/security"
    | "/account/provider/callback"
    | "/auth/2fa/recovery-codes"
    | "/auth/2fa/totp"
    | "/auth/password/forgot"
    | "/auth/password/reset"
    | "/title/$titleId/watch"
    | "/account"
    | "/auth/2fa"
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/movies"
    | "/account/(my-account)"
    | "/auth/2fa"
    | "/account/verify-email"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/title/$titleId"
    | "/account/(my-account)/security"
    | "/account/provider/callback"
    | "/auth/2fa/recovery-codes"
    | "/auth/2fa/totp"
    | "/auth/password/forgot"
    | "/auth/password/reset"
    | "/title/$titleId/watch"
    | "/account/(my-account)/"
    | "/auth/2fa/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MoviesRoute: typeof MoviesRoute
  AccountmyAccountRouteRoute: typeof AccountmyAccountRouteRouteWithChildren
  AccountVerifyEmailRoute: typeof AccountVerifyEmailRoute
  TitleTitleIdRoute: typeof TitleTitleIdRouteWithChildren
  AccountProviderCallbackRoute: typeof AccountProviderCallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/movies": {
      id: "/movies"
      path: "/movies"
      fullPath: "/movies"
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/title/$titleId": {
      id: "/title/$titleId"
      path: "/title/$titleId"
      fullPath: "/title/$titleId"
      preLoaderRoute: typeof TitleTitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/sign-up": {
      id: "/auth/sign-up"
      path: "/sign-up"
      fullPath: "/auth/sign-up"
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/sign-in": {
      id: "/auth/sign-in"
      path: "/sign-in"
      fullPath: "/auth/sign-in"
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/account/verify-email": {
      id: "/account/verify-email"
      path: "/account/verify-email"
      fullPath: "/account/verify-email"
      preLoaderRoute: typeof AccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/2fa": {
      id: "/auth/2fa"
      path: "/2fa"
      fullPath: "/auth/2fa"
      preLoaderRoute: typeof Auth2faRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/account/(my-account)": {
      id: "/account/(my-account)"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AccountmyAccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/2fa/": {
      id: "/auth/2fa/"
      path: "/"
      fullPath: "/auth/2fa/"
      preLoaderRoute: typeof Auth2faIndexRouteImport
      parentRoute: typeof Auth2faRouteRoute
    }
    "/account/(my-account)/": {
      id: "/account/(my-account)/"
      path: "/"
      fullPath: "/account/"
      preLoaderRoute: typeof AccountmyAccountIndexRouteImport
      parentRoute: typeof AccountmyAccountRouteRoute
    }
    "/title/$titleId/watch": {
      id: "/title/$titleId/watch"
      path: "/watch"
      fullPath: "/title/$titleId/watch"
      preLoaderRoute: typeof TitleTitleIdWatchRouteImport
      parentRoute: typeof TitleTitleIdRoute
    }
    "/auth/password/reset": {
      id: "/auth/password/reset"
      path: "/password/reset"
      fullPath: "/auth/password/reset"
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/password/forgot": {
      id: "/auth/password/forgot"
      path: "/password/forgot"
      fullPath: "/auth/password/forgot"
      preLoaderRoute: typeof AuthPasswordForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/auth/2fa/totp": {
      id: "/auth/2fa/totp"
      path: "/totp"
      fullPath: "/auth/2fa/totp"
      preLoaderRoute: typeof Auth2faTotpRouteImport
      parentRoute: typeof Auth2faRouteRoute
    }
    "/auth/2fa/recovery-codes": {
      id: "/auth/2fa/recovery-codes"
      path: "/recovery-codes"
      fullPath: "/auth/2fa/recovery-codes"
      preLoaderRoute: typeof Auth2faRecoveryCodesRouteImport
      parentRoute: typeof Auth2faRouteRoute
    }
    "/account/provider/callback": {
      id: "/account/provider/callback"
      path: "/account/provider/callback"
      fullPath: "/account/provider/callback"
      preLoaderRoute: typeof AccountProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account/(my-account)/security": {
      id: "/account/(my-account)/security"
      path: "/security"
      fullPath: "/account/security"
      preLoaderRoute: typeof AccountmyAccountSecurityRouteImport
      parentRoute: typeof AccountmyAccountRouteRoute
    }
  }
}

interface Auth2faRouteRouteChildren {
  Auth2faRecoveryCodesRoute: typeof Auth2faRecoveryCodesRoute
  Auth2faTotpRoute: typeof Auth2faTotpRoute
  Auth2faIndexRoute: typeof Auth2faIndexRoute
}

const Auth2faRouteRouteChildren: Auth2faRouteRouteChildren = {
  Auth2faRecoveryCodesRoute: Auth2faRecoveryCodesRoute,
  Auth2faTotpRoute: Auth2faTotpRoute,
  Auth2faIndexRoute: Auth2faIndexRoute,
}

const Auth2faRouteRouteWithChildren = Auth2faRouteRoute._addFileChildren(
  Auth2faRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  Auth2faRouteRoute: typeof Auth2faRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  Auth2faRouteRoute: Auth2faRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AccountmyAccountRouteRouteChildren {
  AccountmyAccountSecurityRoute: typeof AccountmyAccountSecurityRoute
  AccountmyAccountIndexRoute: typeof AccountmyAccountIndexRoute
}

const AccountmyAccountRouteRouteChildren: AccountmyAccountRouteRouteChildren = {
  AccountmyAccountSecurityRoute: AccountmyAccountSecurityRoute,
  AccountmyAccountIndexRoute: AccountmyAccountIndexRoute,
}

const AccountmyAccountRouteRouteWithChildren =
  AccountmyAccountRouteRoute._addFileChildren(
    AccountmyAccountRouteRouteChildren,
  )

interface TitleTitleIdRouteChildren {
  TitleTitleIdWatchRoute: typeof TitleTitleIdWatchRoute
}

const TitleTitleIdRouteChildren: TitleTitleIdRouteChildren = {
  TitleTitleIdWatchRoute: TitleTitleIdWatchRoute,
}

const TitleTitleIdRouteWithChildren = TitleTitleIdRoute._addFileChildren(
  TitleTitleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MoviesRoute: MoviesRoute,
  AccountmyAccountRouteRoute: AccountmyAccountRouteRouteWithChildren,
  AccountVerifyEmailRoute: AccountVerifyEmailRoute,
  TitleTitleIdRoute: TitleTitleIdRouteWithChildren,
  AccountProviderCallbackRoute: AccountProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
