# Generated by Django 5.2.10 on 2026-01-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_remove_episode_duration_remove_title_duration'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='titles.episode')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Entry',
                'verbose_name_plural': 'History Entries',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, help_text='Titles watched by the user.', related_name='users_who_watched', through='users.HistoryEntry', to='titles.title', verbose_name='History'),
        ),
        migrations.CreateModel(
            name='SavedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_titles_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Title',
                'verbose_name_plural': 'Saved Titles',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='my_list',
            field=models.ManyToManyField(blank=True, help_text='Titles saved by the user to their personal list.', related_name='users_who_listed', through='users.SavedTitle', to='titles.title', verbose_name='My List'),
        ),
        migrations.AddConstraint(
            model_name='historyentry',
            constraint=models.UniqueConstraint(fields=('user', 'title', 'episode'), name='unique_user_title_episode_history', violation_error_message='This title is already in your history.'),
        ),
        migrations.AddConstraint(
            model_name='savedtitle',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_title_list', violation_error_message='You have already saved this title.'),
        ),
    ]
