# Generated by Django 5.2.10 on 2026-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historyentry_user_history_savedtitle_user_my_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='status',
            field=models.CharField(choices=[('WATCHING', 'Watching'), ('WATCHED', 'Watched')], default='WATCHING', help_text='The current status of the history entry', max_length=10),
        ),
    ]
