# Generated by Django 5.2.8 on 2025-11-15 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the genre', primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='A unique identifier for the genre', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Name of the genre (e.g., Action, Comedy)', max_length=100)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the title', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The official title of the movie or series', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief summary or synopsis')),
                ('content_type', models.CharField(choices=[('MOVIE', 'Movie'), ('SERIES', 'Series')], default='MOVIE', help_text='The type of content (Movie or Series)', max_length=10)),
                ('release_date', models.DateField(blank=True, help_text='The original release date', null=True)),
                ('poster', models.ImageField(blank=True, help_text='Vertical poster image (portrait)', null=True, upload_to='posters/')),
                ('cover', models.ImageField(blank=True, help_text='Horizontal cover image (backdrop)', null=True, upload_to='covers/')),
                ('trailer_url', models.URLField(blank=True, help_text='Link to the official YouTube trailer', max_length=255)),
                ('genres', models.ManyToManyField(blank=True, help_text='Select one or more genres for this title', related_name='titles', to='titles.genre')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
                'ordering': ['-release_date', 'title'],
            },
        ),
    ]
