# Generated by Django 5.2.8 on 2025-11-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='The duration in minutes', null=True),
        ),
    ]
