# Generated by Django 5.2.9 on 2025-12-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, help_text='The unique identifier from The Movie Database (TMDB)', null=True, unique=True),
        ),
    ]
