# Generated by Django 5.2.8 on 2025-11-16 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The average rating out of 10', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
