# Generated by Django 5.2.9 on 2025-12-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_tmdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name_en',
            new_name='name_en_us',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='description_en',
            new_name='description_en_us',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title_en',
            new_name='title_en_us',
        ),
    ]
