# Generated by Django 5.2.9 on 2025-12-09 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_rename_name_en_genre_name_en_us_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-release_date'], 'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
        migrations.AddField(
            model_name='title',
            name='added_by',
            field=models.CharField(choices=[('TMDB', 'The Movie Database'), ('MANUAL', 'Manual')], default='MANUAL', help_text='Indicates how the title was added to the database', max_length=10),
        ),
        migrations.AddField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when the title was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('RELEASED', 'Released'), ('CANCELED', 'Canceled'), ('AWAITING_REVIEW', 'Awaiting Review')], default='AWAITING_REVIEW', help_text='The current status of the title', max_length=20),
        ),
    ]
