# Generated by Django 5.2.9 on 2025-12-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_alter_title_options_title_added_by_title_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, help_text='The TMDB ID of the title', null=True),
        ),
    ]
