# Generated by Django 5.2.8 on 2025-11-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_alter_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='cast',
            field=models.TextField(blank=True, help_text='List of main cast members'),
        ),
    ]
