# Generated by Django 5.2.9 on 2025-12-11 16:35

import django.core.validators
import django.db.models.deletion
import dkmovie.titles.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_alter_title_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the title was last updated'),
        ),
        migrations.AlterField(
            model_name='title',
            name='cover',
            field=models.ImageField(blank=True, help_text='Horizontal cover image (backdrop)', null=True, upload_to=dkmovie.titles.models.cover_path),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, help_text='Vertical poster image (portrait)', null=True, upload_to=dkmovie.titles.models.poster_path),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the season', primary_key=True, serialize=False)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, help_text='The TMDB ID of the season', null=True, unique=True)),
                ('number', models.PositiveIntegerField(default=1, help_text='Season number')),
                ('name', models.CharField(help_text='Season name', max_length=255)),
                ('name_en_us', models.CharField(help_text='Season name', max_length=255, null=True)),
                ('name_pt_br', models.CharField(help_text='Season name', max_length=255, null=True)),
                ('overview', models.TextField(blank=True, help_text='Season overview')),
                ('overview_en_us', models.TextField(blank=True, help_text='Season overview', null=True)),
                ('overview_pt_br', models.TextField(blank=True, help_text='Season overview', null=True)),
                ('poster', models.ImageField(blank=True, help_text='Season poster image', null=True, upload_to=dkmovie.titles.models.season_path)),
                ('air_date', models.DateField(blank=True, help_text='The date when the season premiered', null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='The average rating out of 10', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the season was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the season was last updated')),
                ('title', models.ForeignKey(help_text='The title to which this season belongs', on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='titles.title')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the episode', primary_key=True, serialize=False)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, help_text='The TMDB ID of the episode', null=True, unique=True)),
                ('number', models.PositiveIntegerField(default=1, help_text='Episode number')),
                ('name', models.CharField(help_text='Episode name', max_length=255)),
                ('name_en_us', models.CharField(help_text='Episode name', max_length=255, null=True)),
                ('name_pt_br', models.CharField(help_text='Episode name', max_length=255, null=True)),
                ('overview', models.TextField(blank=True, help_text='Episode overview')),
                ('overview_en_us', models.TextField(blank=True, help_text='Episode overview', null=True)),
                ('overview_pt_br', models.TextField(blank=True, help_text='Episode overview', null=True)),
                ('still', models.ImageField(blank=True, help_text='Episode still image', null=True, upload_to=dkmovie.titles.models.episode_path)),
                ('air_date', models.DateField(blank=True, help_text='The date when the episode premiered', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='The duration in minutes', null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='The average rating out of 10', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the episode was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the episode was last updated')),
                ('season', models.ForeignKey(help_text='The season to which this episode belongs', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='titles.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['season__number', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('title', 'number'), name='unique_season_per_title'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='unique_episode_per_season'),
        ),
    ]
