# Generated by Django 5.2.9 on 2025-12-22 23:06

import dkmovie.titles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_title_updated_at_alter_title_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, help_text='The video file for the episode', null=True, upload_to=dkmovie.titles.models.episode_video_path),
        ),
        migrations.AddField(
            model_name='title',
            name='video_file',
            field=models.FileField(blank=True, help_text='The video file for the movie', null=True, upload_to=dkmovie.titles.models.video_path),
        ),
    ]
