# Generated by Django 5.2.9 on 2026-01-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_title_updated_at_alter_title_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='title',
            name='duration',
        ),
    ]
