# Generated by Django 5.2.9 on 2025-12-27 06:42

import django.db.models.deletion
import dkmovie.titles.models
import dkmovie.upload.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('titles', '0006_title_updated_at_alter_title_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='title',
            name='duration',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the video', primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='The ID of the object this video belongs to')),
                ('source_file', dkmovie.upload.fields.S3FileField(blank=True, help_text='The video file', max_length=500, null=True, upload_to=dkmovie.titles.models.source_file_path)),
                ('duration', models.PositiveIntegerField(default=0, help_text='The duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the video was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the video was last updated')),
                ('content_type', models.ForeignKey(help_text='The type of the object this video belongs to (Title or Episode)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='titles_vide_content_25c39b_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_video_per_object')],
            },
        ),
    ]
