# Generated by Django 5.2.9 on 2025-12-26 16:35

import dkmovie.titles.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_title_updated_at_alter_title_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=dkmovie.titles.fields.S3FileField(blank=True, help_text='The video file for the episode', max_length=500, null=True, upload_to='uploads/episodes/'),
        ),
        migrations.AddField(
            model_name='title',
            name='video_file',
            field=dkmovie.titles.fields.S3FileField(blank=True, help_text='The video file for the movie', max_length=500, null=True, upload_to='uploads/movies/'),
        ),
    ]
