# Generated by Django 5.2.9 on 2025-12-28 00:42

import config.storages
import dkmovie.titles.models
import dkmovie.upload.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_remove_episode_duration_remove_title_duration_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_file',
            field=dkmovie.upload.fields.S3FileField(blank=True, help_text='The video file', max_length=500, null=True, storage=config.storages.PrivateMediaStorage(), upload_to=dkmovie.titles.models.source_file_path),
        ),
    ]
