# Generated by Django 5.2.9 on 2025-12-26 17:47

import dkmovie.titles.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_episode_video_file_title_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=dkmovie.titles.fields.S3FileField(blank=True, help_text='The video file for the episode', max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='title',
            name='video_file',
            field=dkmovie.titles.fields.S3FileField(blank=True, help_text='The video file for the movie', max_length=500, null=True, upload_to=''),
        ),
    ]
