# Generated by Django 5.2.9 on 2025-12-30 21:49

import config.storages
import dkmovie.titles.models
import dkmovie.upload.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_alter_video_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=dkmovie.upload.fields.S3FileField(blank=True, help_text='The HLS master playlist file', max_length=500, null=True, storage=config.storages.PrivateMediaStorage(), upload_to=dkmovie.titles.models.hls_playlist_path),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed'),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='The status of the video processing', max_length=20),
        ),
    ]
